// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSjil3Pfx4dNkWd2NTLmEqTFhQXCSPuPk',
    appId: '1:319737852796:web:360fb6764126bb0c496af9',
    messagingSenderId: '319737852796',
    projectId: 'testing-modul6',
    authDomain: 'testing-modul6.firebaseapp.com',
    storageBucket: 'testing-modul6.firebasestorage.app',
    measurementId: 'G-V2V4EK3F8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5zcGssZEHUtR7vIaC_PX9bjlUzaaeMVs',
    appId: '1:319737852796:android:bfd6ef69179cb1b2496af9',
    messagingSenderId: '319737852796',
    projectId: 'testing-modul6',
    storageBucket: 'testing-modul6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDN2Xv26d1Ren6x7KGbFwkSzAzerEsznw',
    appId: '1:319737852796:ios:aa999d0949c00ed9496af9',
    messagingSenderId: '319737852796',
    projectId: 'testing-modul6',
    storageBucket: 'testing-modul6.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDN2Xv26d1Ren6x7KGbFwkSzAzerEsznw',
    appId: '1:319737852796:ios:aa999d0949c00ed9496af9',
    messagingSenderId: '319737852796',
    projectId: 'testing-modul6',
    storageBucket: 'testing-modul6.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSjil3Pfx4dNkWd2NTLmEqTFhQXCSPuPk',
    appId: '1:319737852796:web:292cf037fc3d88cb496af9',
    messagingSenderId: '319737852796',
    projectId: 'testing-modul6',
    authDomain: 'testing-modul6.firebaseapp.com',
    storageBucket: 'testing-modul6.firebasestorage.app',
    measurementId: 'G-XHBPZFMHGE',
  );
}
