// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzj7i6D4KvdWljju_E5lSZV4WEgjFOHFI',
    appId: '1:329784755398:web:abfd9282f86973f96503c7',
    messagingSenderId: '329784755398',
    projectId: 'fir-modul6-c3520',
    authDomain: 'fir-modul6-c3520.firebaseapp.com',
    storageBucket: 'fir-modul6-c3520.firebasestorage.app',
    measurementId: 'G-EDWMD1V5L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu-7OOuxTf-nkRRygvdEsUkUwhl4qW8fg',
    appId: '1:329784755398:android:a009637c0357f5186503c7',
    messagingSenderId: '329784755398',
    projectId: 'fir-modul6-c3520',
    storageBucket: 'fir-modul6-c3520.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzj7i6D4KvdWljju_E5lSZV4WEgjFOHFI',
    appId: '1:329784755398:web:1793fd7c082ee6266503c7',
    messagingSenderId: '329784755398',
    projectId: 'fir-modul6-c3520',
    authDomain: 'fir-modul6-c3520.firebaseapp.com',
    storageBucket: 'fir-modul6-c3520.firebasestorage.app',
    measurementId: 'G-CC8S3NPCVG',
  );
}
